### PR TITLE
Add type container docs for dry-schema

### PR DESCRIPTION
**Pull request by Morozzzko**
Finally added docs for the type containers in dry-schema

### CODE REVIEW

**Comment by solnic** [comment]
@Morozzzko hmm weird, it didn't show up on the website

**Comment by Morozzzko** [comment]
Master wasn't built after the merge, as it seems

**Comment by Morozzzko** [comment]
изображение

No status reported, it must be the root of the problem

**Comment by solnic** [comment]
@Morozzzko it was built https://travis-ci.org/dry-rb/dry-rb.org/builds/550805113

**Comment by Morozzzko** [comment]
The build you linked to shows up in the `Pull Requests` tab, but not in the `builds`. When you tried restarting it (?) it actually reported something.

изображение

**Pull request merged**
