### PR TITLE
Add the missing link to `type-specs` page

### PR DESCRIPTION
**Pull request by v-kolesnikov**

### CODE REVIEW

**Comment by Morozzzko** [comment]
Thanks! It seems to be a duplicate of #190, though. I think we should probably address the issues raised during the conversations https://github.com/dry-rb/dry-rb.org/pull/190#issuecomment-314464087

**Comment by v-kolesnikov** [comment]
Oh, have not seen #190, my bad.
My colleague asked me (as a dry-rb expert 😄) what is `config.type_specs` because he couldn't find any documentation of this topic... I think it would be better to have this page on the site.

**Comment by flash-gordon** [comment]
I think you're right. Since we have separate docs for 1.0 it won't hurt. Mind to re-open the PR? It looks like I can't do it from here

**Comment by Morozzzko** [comment]
I have to agree here: I had to answer questions about `type_specs` a couple of times. I would love to see them live

@v-kolesnikov do you think the `type-specs` docs are up to date? Do we need any extra work to update them?

**Comment by v-kolesnikov** [comment]
@Morozzzko I think the `type-specs` doc page is good now. 

> BTW I think we can't reopen PR because the source branch has been deleted

Try with #190

**Comment by flash-gordon** [comment]
It has conflicts there :(

**Comment by v-kolesnikov** [comment]
OK. I reopened it as #295

**Pull request closed without merging**
