### PR TITLE
added type_specs to sidebar

### PR DESCRIPTION
**Pull request by chapuzzo**

### CODE REVIEW

**Comment by flash-gordon** [comment]
@solnic any reason why it's not there?

**Comment by solnic** [comment]
@flash-gordon yes, it needs to be rewritten/updated/improved first

**Comment by chapuzzo** [comment]
@solnic what needs to be rewritten/updated/improved first, docs or type_specs code itself? I didn't find anywhere info about this feature. Googling and I found this doc, but couldn't find it otherwise because it was not linked.

**Comment by solnic** [comment]
This isn't a first-class feature yet. It will be in 1.0.0 but I'm not yet sure if it'll look the same from API pov. We could add docs about it though.

**Comment by flash-gordon** [comment]
Let's close it, 1.0 is out and it's the recommended way to proceed.

**Pull request closed without merging**
