### PR TITLE
Fix broken links for dry-validation

### PR DESCRIPTION
**Pull request by Morozzzko**
Addresses issue raised by @cchausfeld in #145 
https://github.com/dry-rb/dry-rb.org/issues/145#issuecomment-470534171

I'll submit another PR with instructions on adding docs for multiple gem versions later.

What I've done in this PR:

* Added symlinks from `gems/dry-validation` to `gems/dry-validation/0.13`. It's important because the old links died
* Kept `gems/dry-validation/index.html.md` linked to `1.0.0`, as we want new people to dive into the newer version
* Renamed `1.0.0.alpha1` into `1.0.0`, since we don't want to handle any more dead links. It's going to display as `'1.0.0.alpha'`, but the link would be a proper `1.0.0`

### CODE REVIEW

**Comment by Morozzzko** [comment]
By the way, I've realized that the `fallback` option is kind of broken. My bad. I'll submit a fix later

**Comment by timriley** [comment]
@Morozzzko Do we really want the default dry-validation docs page to go to 1.0.0, even though it's still in alpha? Could we make it continue to go to the last 0.x release by default, instead, and keep the 1.0.0 docs around as a selectable option?

**Comment by Morozzzko** [comment]
@timriley actually yeah, you're right. We probably don't want that for now. `1.0.0` needs a little more docs. 

It would actually _temporarily_ solve the problem with `fallback_version`. I'll switch `index` to `0.13` right now, and we'll come back to update things later

**Comment by Morozzzko** [comment]
Woopsie. Fixed here now. Sorry 🙈

**Pull request merged**
