### PR TITLE
Update documentation to support refined DSL

### PR DESCRIPTION
**Pull request by coop**
Don't merge until https://github.com/dry-rb/dry-validation/pull/109 has been merged and (probably) released.

### CODE REVIEW

**Comment by coop** [comment]
Awkwardly I deleted my fork of this repo before this got merged but GitHub has kept the changes around, pheww!

**Comment by tak1n** [comment]
cc @timriley, @AMHOL 

As the pr in dry-v got merged this can be merged.

**Comment by timriley** [comment]
Thanks @tak1n – I think it might be best to wait until this work is released as an installable gem before we merge the docs?

I'd be happy for this to go in whenever that release happens. Ping me again if you need a hand doing it :)

**Comment by coop** [comment]
I agree. We should hold off until it is released. It sounds like @solnic
wants to cut a release when he gets back.

**Comment by timriley** [comment]
Looks like the docs are all up to date now :) Thanks!

**Pull request closed without merging**
