### PR TITLE
Search functionality

### LINKED ISSUE #310: Add search functionality
dry-rb.org has quite a lot of docs it would be nice to have a search bar

I like https://www.algolia.com
Example: http://guides.hanamirb.org/introduction/getting-started/
Integration example: https://github.com/hanami/guides/pull/2/files

### PR DESCRIPTION
**Pull request by skryukov**
This PR adds search functionality with https://community.algolia.com/docsearch/

_WIP until one of the maintainers gain an API key by applying to the Docsearch community program (link above)._

image
image
image

always open on mobile:
image

Closes #310

### CODE REVIEW

**Comment by solnic** [comment]
> WIP until one of the maintainers gain an API key by applying to the Docsearch community program (link above).

@skryukov I applied today. I'll get back to you once I have the key 😄

**Comment by solnic** [comment]
@skryukov we got it:

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
apiKey: '77902a61218a8fbaa06a6125cb6589a7',
indexName: 'dry-rb',
inputSelector: '### REPLACE ME ####',
debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

**Comment by skryukov** [comment]
@solnic It would be great to add library versions to the headers, to distinguish them in the search results. But I think I will do this with another PR and this one good enough to be merged as-is.

**Comment by solnic** [comment]
@skryukov yeah totally, we can just keep improving it in separate PRs. I'm super stoked we've got search!

**Pull request merged**
