### PR TITLE
[WIP] Dry struct documentation

### PR DESCRIPTION
**Pull request by backus**
In this PR I'm aiming to address missing documentation for dry-struct which mainly involves improving documentation for dry-types hash schemas. This PR will need some additional styling for tables which I think are the best way to give a breakdown of behavior differences

### CODE REVIEW

**Comment by solnic** [comment]
I added styles and expanded intro a tiny bit. It's now merged :)

**Comment by backus** [comment]
Thanks @solnic!

**Comment by solnic** [comment]
@backus uhm, likewise :) ps. it's published already

**Comment by backus** [comment]
I saw. Looks great :smile:

**Pull request merged**
