### PR TITLE
Add docs for dry-types `Types.Contract`

### PR DESCRIPTION
**Pull request by waiting-for-dev**
Refs dry-rb/dry-types#323

### CODE REVIEW

**Comment by solnic** [comment]
Please revert this. It is not released AND we renamed it to Interface

**Comment by davydovanton** [comment]
oh, sorry my bad 😞

**Comment by solnic** [comment]
@davydovanton don’t worry about this. It is one of the many reasons why I think we should have docs as part of individual project repos. Mistakes like that will be easier to avoid :)

**Comment by davydovanton** [comment]
@solnic yep, agree. I think it will be better. Also, it will be better to work with different gem versions.

**Pull request merged**
